# SPDX-License-Identifier: AGPL-3.0-or-later
# pylint: disable=global-statement
# pylint: disable=missing-module-docstring, missing-class-docstring

__all__ = ["get_network"]

import typing as t
from collections.abc import Generator


import atexit
import asyncio
import ipaddress
import math
import re
import secrets
from itertools import cycle
from urllib.parse import urlsplit, urlunsplit

from curl_cffi import CurlHttpVersion
from curl_cffi.requests.exceptions import (
    ConnectionError as CurlConnectionError,
    ProxyError,
    RequestException,
)

import searx
from searx import logger, sxng_debug
from searx.extended_types import SXNG_Response
from searx.settings_defaults import TOR_CIRCUITS_MAX, TOR_ONLY, check_tor_only
from .client import DEFAULT_IMPERSONATE, AsyncClient, new_client, get_loop
from .raise_for_httperror import raise_for_httperror

logger = logger.getChild('network')
DEFAULT_NAME = '__DEFAULT__'
NETWORKS: dict[str, "Network"] = {}
NOT_INITIALIZED_MESSAGE = f'{TOR_ONLY}: the network is not initialized'
# requests compatibility when reading proxy settings from settings.yml
PROXY_PATTERN_MAPPING = {
    'http': 'http://',
    'https': 'https://',
    'socks4': 'socks4://',
    'socks5': 'socks5://',
    'socks5h': 'socks5h://',
    'http:': 'http://',
    'https:': 'https://',
    'socks4:': 'socks4://',
    'socks5:': 'socks5://',
    'socks5h:': 'socks5h://',
}

ADDRESS_MAPPING = {'ipv4': '0.0.0.0', 'ipv6': '::'}

TOR_CIRCUIT_SALT: str = secrets.token_hex(4)
"""Per-process salt of the SOCKS credentials generated by
:py:obj:`expand_tor_circuits`, a restart of SearXNG gets fresh Tor circuits."""

_TOR_CIRCUIT_SALT_RE = re.compile(r'[A-Za-z0-9-]+')

TOR_CHECK_RETRY_DELAYS: tuple[float, ...] = (2, 5)
"""Delays (seconds) before the retries of a failed Tor check at startup, see
:py:obj:`check_network_configuration`."""


def expand_tor_circuits(
    proxies: str | dict[str, t.Any] | None,
    n: int,  # pylint: disable=invalid-name
    salt: str | None = None,
) -> str | dict[str, t.Any] | None:
    """Expand each plain ``socks5h://host:port`` proxy URL into ``n`` URLs with
    distinct SOCKS credentials (``socks5h://sxng-<i>:<salt>@host:port``).

    Tor isolates streams with different SOCKS credentials on different circuits
    (``IsolateSOCKSAuth``, enabled by default), so the round-robin over these
    URLs spreads the requests over ``n`` circuits (exit nodes).

    Only ``socks5h://`` URLs without credentials are expanded, other URLs are
    returned unchanged.  With ``n < 2`` the proxies are returned unchanged, a
    ``str`` value is returned as ``{'all://': [...]}`` when it is expanded.
    """
    if not proxies or n < 2 or not isinstance(proxies, (str, dict)):
        return proxies
    salt = TOR_CIRCUIT_SALT if salt is None else salt
    if not _TOR_CIRCUIT_SALT_RE.fullmatch(salt):
        raise ValueError(f'invalid salt for the Tor circuits: {salt!r}')

    def expand(urls: str | list[str]) -> str | list[str]:
        result: list[str] = []
        expanded = False
        for url in [urls] if isinstance(urls, str) else urls:
            parts = urlsplit(url)
            if not url.startswith('socks5h://') or not parts.netloc or '@' in parts.netloc:
                result.append(url)
                continue
            for i in range(n):
                netloc = f'sxng-{i}:{salt}@{parts.netloc}'
                result.append(urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment)))
            expanded = True
        return result if expanded else urls

    if isinstance(proxies, str):
        urls = expand(proxies)
        return proxies if isinstance(urls, str) else {'all://': urls}
    return {pattern: expand(urls) for pattern, urls in proxies.items()}


def url_for_log(url: str) -> str:
    """Returns the URL as it may be written to the log files.

    The URL of an engine request contains the search terms (in the query string
    or in the path), outside of debug mode only the scheme and the host (without
    credentials) are returned, the search terms are not stored in the logs of a
    production instance.
    """
    if searx.sxng_debug:
        return url
    parts = urlsplit(url)
    host = parts.netloc.rsplit('@', 1)[-1]
    return f'{parts.scheme}://{host}/...' if host else '...'


@t.final
class Network:

    __slots__ = (
        'enable_http',
        'verify',
        'enable_http2',
        'enable_http3',
        'max_connections',
        'local_addresses',
        'proxies',
        'using_tor_proxy',
        'max_redirects',
        'retries',
        'retry_on_http_error',
        'tor_circuits',
        '_local_addresses_cycle',
        '_proxies_cycle',
        '_proxy_pool',
        '_clients',
        '_logger',
    )

    _TOR_CHECK_RESULT = {}
    _CLIENT_KWARGS = ('verify', 'max_redirects', 'impersonate', 'curl_options', 'enable_http3', 'proxy_index')

    def __init__(
        # pylint: disable=too-many-arguments
        self,
        enable_http: bool = True,
        verify: bool = True,
        enable_http2: bool = False,
        enable_http3: bool = False,
        max_connections: int = None,  # pyright: ignore[reportArgumentType]
        proxies: str | dict[str, t.Any] | None = None,
        using_tor_proxy: bool = False,
        local_addresses: str | list[str] | None = None,
        retries: int = 0,
        retry_on_http_error: bool = False,
        max_redirects: int = 30,
        logger_name: str = None,  # pyright: ignore[reportArgumentType]
        *,
        tor_circuits: int = 0,
    ):

        if not 0 <= tor_circuits <= TOR_CIRCUITS_MAX:
            raise ValueError(f'tor_circuits: {tor_circuits} is not in the range 0..{TOR_CIRCUITS_MAX}')
        self.enable_http = enable_http
        self.verify = verify
        self.enable_http2 = enable_http2
        self.enable_http3 = enable_http3
        self.max_connections = max_connections
        self.using_tor_proxy = using_tor_proxy
        self.tor_circuits = tor_circuits
        if using_tor_proxy and tor_circuits >= 2:
            self.proxies = expand_tor_circuits(proxies, tor_circuits)
        else:
            self.proxies = proxies
        self.local_addresses = local_addresses
        self.retries = retries
        self.retry_on_http_error = retry_on_http_error
        self.max_redirects = max_redirects
        self._local_addresses_cycle = self.get_ipaddress_cycle()
        self._proxies_cycle = self.get_proxy_cycles()
        self._clients: dict[tuple[t.Any, ...], AsyncClient] = {}
        self._logger = logger.getChild(logger_name) if logger_name else logger
        self.check_parameters()
        self._proxy_pool = self.get_proxy_pool()

    def check_parameters(self):
        for address in self.iter_ipaddresses():
            if '/' in address:
                ipaddress.ip_network(address, False)
            else:
                ipaddress.ip_address(address)

        if self.proxies is not None and not isinstance(self.proxies, (str, dict)):
            raise ValueError('proxies type has to be str, dict or None')

        if self.using_tor_proxy:
            self.check_tor_parameters()

    def check_tor_parameters(self):
        """With ``using_tor_proxy``, each request has to be sent to Tor: all
        proxy URLs are ``socks5h://`` URLs and there is a proxy for each scheme
        the network may use (``all://``, or ``https://`` and, when HTTP is
        enabled, ``http://``).  Otherwise a :py:obj:`ValueError` is raised."""
        name = self._logger.name
        patterns: set[str] = set()
        for pattern, proxy_urls in self.iter_proxies():
            patterns.add(pattern)
            for proxy_url in proxy_urls:
                if not proxy_url.startswith('socks5h://'):
                    # don't log the proxy URL, it may contain credentials
                    scheme = urlsplit(proxy_url).scheme or '?'
                    raise ValueError(
                        f'{name}: using_tor_proxy requires socks5h:// proxies,'
                        f' the {pattern} proxy is a {scheme}:// proxy'
                    )
        if 'all://' in patterns:
            return
        missing = [scheme for scheme in ('https://', 'http://') if scheme not in patterns]
        if not self.enable_http and 'http://' in missing:
            missing.remove('http://')
        if missing:
            raise ValueError(
                f"{name}: using_tor_proxy requires a proxy for every scheme, missing: {', '.join(missing)}"
                " (set an 'all://' proxy, or 'https://' and 'http://' proxies)"
            )

    def iter_ipaddresses(self) -> Generator[str]:
        local_addresses = self.local_addresses
        if not local_addresses:
            return
        if isinstance(local_addresses, str):
            local_addresses = [local_addresses]
        yield from local_addresses

    def get_ipaddress_cycle(self):
        while True:
            count = 0
            for address in self.iter_ipaddresses():
                if '/' in address:
                    for a in ipaddress.ip_network(address, False).hosts():
                        yield str(a)
                        count += 1
                else:
                    a = ipaddress.ip_address(address)
                    yield str(a)
                    count += 1
            if count == 0:
                yield None

    def iter_proxies(self) -> Generator[tuple[str, list[str]]]:
        if not self.proxies:
            return
        if isinstance(self.proxies, str):
            yield 'all://', [self.proxies]
        else:
            for pattern, proxy_url in self.proxies.items():
                pattern: str = PROXY_PATTERN_MAPPING.get(pattern, pattern)
                if isinstance(proxy_url, str):
                    proxy_url = [proxy_url]
                yield pattern, proxy_url

    def get_proxy_cycles(self) -> Generator[tuple[tuple[str, str], ...], str, str]:  # not sure type is correct
        proxy_settings: dict[str, t.Any] = {}
        for pattern, proxy_urls in self.iter_proxies():
            proxy_settings[pattern] = cycle(proxy_urls)
        while True:
            # pylint: disable=stop-iteration-return
            yield tuple((pattern, next(proxy_url_cycle)) for pattern, proxy_url_cycle in proxy_settings.items())

    def get_proxy_pool(self) -> list[tuple[tuple[str, str], ...]]:
        """Returns the distinct proxy tuples in the order they are yielded by
        :py:obj:`Network.get_proxy_cycles`.  The length of the pool is the least
        common multiple of the lengths of the proxy lists (``[()]`` when no
        proxy is configured)."""
        proxy_settings: dict[str, list[str]] = {}
        for pattern, proxy_urls in self.iter_proxies():
            proxy_settings[pattern] = list(proxy_urls)
        if not proxy_settings:
            return [()]
        size = math.lcm(*(len(proxy_urls) for proxy_urls in proxy_settings.values()))
        return [
            tuple((pattern, proxy_urls[i % len(proxy_urls)]) for pattern, proxy_urls in proxy_settings.items())
            for i in range(size)
        ]

    @property
    def proxy_pool(self) -> list[tuple[tuple[str, str], ...]]:
        """The proxy tuples of this network, a request can select one of them by
        its index: ``searx.network.get(url, proxy_index=i)``."""
        return list(self._proxy_pool)

    _HTTP_VERSION = {
        int(CurlHttpVersion.V1_0): "HTTP/1.0",
        int(CurlHttpVersion.V1_1): "HTTP/1.1",
        int(CurlHttpVersion.V2_0): "HTTP/2",
        int(CurlHttpVersion.V2TLS): "HTTP/2",
        int(CurlHttpVersion.V2_PRIOR_KNOWLEDGE): "HTTP/2",
        int(CurlHttpVersion.V3): "HTTP/3",
        int(CurlHttpVersion.V3ONLY): "HTTP/3",
    }

    async def log_response(self, response: SXNG_Response):
        request = response.request
        http_version = self._HTTP_VERSION.get(response.http_version, str(response.http_version))
        status = f"{response.status_code} {response.reason}"
        response_line = f"{http_version} {status}"
        content_type = response.headers.get("Content-Type")
        content_type = f' ({content_type})' if content_type else ''
        method = request.method if request else "?"
        url = request.url if request else response.url
        self._logger.debug(f'HTTP Request: {method} {url} "{response_line}"{content_type}')

    @staticmethod
    async def check_tor_proxy(client: AsyncClient, proxies) -> bool:
        """Returns ``True`` if the requests of ``client`` (with ``proxies``) are
        sent over Tor (asks https://check.torproject.org/api/ip).

        A positive result is cached.  A negative result is only cached when it
        is deterministic (not all proxies are ``socks5h://`` URLs): a failed
        request or an unexpected answer can be transient, the next client with
        these proxies is checked again."""
        if proxies in Network._TOR_CHECK_RESULT:
            return Network._TOR_CHECK_RESULT[proxies]

        if not proxies or not all(url.startswith('socks5h://') for _, url in proxies):
            Network._TOR_CHECK_RESULT[proxies] = False
            return False

        try:
            response = await client.get("https://check.torproject.org/api/ip", timeout=15)
            result = response.json()["IsTor"] is True
        except Exception as e:  # pylint: disable=broad-except
            logger.warning("Tor check failed: %s: %s", type(e).__name__, e)
            return False
        if result:
            Network._TOR_CHECK_RESULT[proxies] = True
        else:
            logger.warning("Tor check failed: check.torproject.org reports IsTor != true")
        return result

    async def get_client(
        self,
        verify: bool | None = None,
        max_redirects: int | None = None,
        impersonate: str | None = None,
        curl_options: dict[int, t.Any] | None = None,
        enable_http3: bool | None = None,
        proxy_index: int | None = None,
    ) -> AsyncClient:
        """Returns a client of this network.  By default the proxies are chosen
        round-robin, ``proxy_index`` selects an entry of
        :py:obj:`Network.proxy_pool` (modulo its length) instead."""
        if self is NOT_INITIALIZED:
            # fail closed: no request is sent before initialize() has configured Tor
            raise RuntimeError(NOT_INITIALIZED_MESSAGE)
        verify = self.verify if verify is None else verify
        max_redirects = self.max_redirects if max_redirects is None else max_redirects
        impersonate = impersonate or DEFAULT_IMPERSONATE
        enable_http3 = self.enable_http3 if enable_http3 is None else enable_http3
        local_address = next(self._local_addresses_cycle)
        # proxies is a tuple so it can be part of the key
        if proxy_index is None:
            proxies = next(self._proxies_cycle)
        else:
            proxies = self._proxy_pool[proxy_index % len(self._proxy_pool)]
        curl_key = tuple(sorted((int(k), v) for k, v in (curl_options or {}).items()))
        key = (verify, max_redirects, local_address, proxies, impersonate, curl_key, enable_http3)
        if key not in self._clients or self._clients[key].is_closed:
            client = new_client(
                self.enable_http,
                verify,
                self.enable_http2,
                enable_http3,
                self.max_connections,
                dict(proxies),
                local_address,
                max_redirects,
                impersonate=impersonate,
                curl_options=curl_options,
            )
            if self.using_tor_proxy and not await self.check_tor_proxy(client, proxies):
                await client.aclose()
                raise ProxyError('Network configuration problem: not using Tor')
            other = self._clients.get(key)
            if other is not None and not other.is_closed:
                # a concurrent call has stored a (checked) client in the meantime
                await client.aclose()
                return other
            self._clients[key] = client
        return self._clients[key]

    async def aclose(self):
        async def close_client(client):
            try:
                await client.aclose()
            except RequestException:
                pass

        await asyncio.gather(*[close_client(client) for client in self._clients.values()], return_exceptions=False)

    @staticmethod
    def extract_kwargs_clients(kwargs: dict[str, t.Any]) -> dict[str, t.Any]:
        return {key: kwargs.pop(key) for key in Network._CLIENT_KWARGS if key in kwargs}

    @staticmethod
    def extract_do_raise_for_httperror(kwargs: dict[str, t.Any]):
        do_raise_for_httperror = True
        if 'raise_for_httperror' in kwargs:
            do_raise_for_httperror = kwargs['raise_for_httperror']
            del kwargs['raise_for_httperror']
        return do_raise_for_httperror

    def patch_response(self, response: SXNG_Response, do_raise_for_httperror: bool) -> SXNG_Response:
        if do_raise_for_httperror:
            try:
                raise_for_httperror(response)
            except:
                method = response.request.method if response.request else "?"
                url = response.request.url if response.request else response.url
                self._logger.warning(f"HTTP Request failed: {method} {url_for_log(str(url))}")
                raise
        return response

    def is_valid_response(self, response: SXNG_Response):
        # pylint: disable=too-many-boolean-expressions
        if (
            (self.retry_on_http_error is True and 400 <= response.status_code <= 599)
            or (isinstance(self.retry_on_http_error, list) and response.status_code in self.retry_on_http_error)
            or (isinstance(self.retry_on_http_error, int) and response.status_code == self.retry_on_http_error)
        ):
            return False
        return True

    async def call_client(self, stream: bool, method: str, url: str, **kwargs: t.Any) -> SXNG_Response:
        retries = self.retries
        was_disconnected = False
        do_raise_for_httperror = Network.extract_do_raise_for_httperror(kwargs)
        kwargs_clients = Network.extract_kwargs_clients(kwargs)
        while retries >= 0:  # pragma: no cover
            client = await self.get_client(**kwargs_clients)
            try:
                method = method.upper()
                if stream:
                    return client.stream(method, url, **kwargs)

                response = await client.request(method, url, **kwargs)
                if sxng_debug:
                    await self.log_response(response)
                if self.is_valid_response(response) or retries <= 0:
                    return self.patch_response(response, do_raise_for_httperror)
                await client.aclose()
            except CurlConnectionError as e:
                if not was_disconnected:
                    # the server has closed the connection:
                    # try again without decreasing the retries variable & with a new HTTP client
                    was_disconnected = True
                    await client.aclose()
                    self._logger.warning('ConnectionError: the server has disconnected, retrying')
                    continue
                if retries <= 0:
                    raise e
            except RequestException as e:
                if retries <= 0:
                    raise e
            retries -= 1

    async def request(self, method: str, url: str, **kwargs: t.Any) -> SXNG_Response:
        return await self.call_client(False, method, url, **kwargs)

    async def stream(self, method: str, url: str, **kwargs):
        return await self.call_client(True, method, url, **kwargs)

    @classmethod
    async def aclose_all(cls):
        await asyncio.gather(*[network.aclose() for network in NETWORKS.values()], return_exceptions=False)


def get_network(name: str | None = None) -> "Network":
    return NETWORKS.get(name or DEFAULT_NAME)  # pyright: ignore[reportReturnType]


def check_network_configuration():
    """Checks at startup that the networks send their requests over Tor, raises a
    :py:obj:`RuntimeError` if one of them does not use Tor (Tor-only build: a
    network without ``using_tor_proxy`` or the placeholder of the default
    network before :py:obj:`initialize` fail as well).  A failed check is
    repeated after the delays in :py:obj:`TOR_CHECK_RETRY_DELAYS` (a new Tor
    circuit may need a moment).

    The check stops at the first network that fails (the configuration is
    invalid anyway): when Tor is not reachable, all networks would fail one
    after the other and the (fail-closed) start would take minutes."""

    async def check_client(network: Network, proxy_index: int | None) -> bool:
        # pylint: disable=protected-access
        for delay in (*TOR_CHECK_RETRY_DELAYS, None):
            try:
                await network.get_client(proxy_index=proxy_index)
                return True
            except Exception as e:  # pylint: disable=broad-except
                if delay is None:
                    network._logger.exception('Error')
                    return False
                network._logger.warning('Tor check failed (%s), retry in %s sec', e, delay)
                await asyncio.sleep(delay)
        return False

    async def check() -> bool:
        for name, network in NETWORKS.items():
            if not network.using_tor_proxy:
                logger.error('%s: the network does not use Tor', name)
                return False
            # The default network checks each entry of its proxy pool (each Tor
            # circuit), the results are cached for the networks sharing these
            # proxies.
            proxy_indexes = range(len(network.proxy_pool)) if name == DEFAULT_NAME else [None]
            for proxy_index in proxy_indexes:
                if not await check_client(network, proxy_index):
                    return False
        return True

    if NETWORKS.get(DEFAULT_NAME) is NOT_INITIALIZED:
        raise RuntimeError(NOT_INITIALIZED_MESSAGE)
    future = asyncio.run_coroutine_threadsafe(check(), get_loop())
    if not future.result():
        raise RuntimeError("Invalid network configuration")


def initialize(
    settings_engines: list[dict[str, t.Any]] = None,  # pyright: ignore[reportArgumentType]
    settings_outgoing: dict[str, t.Any] = None,  # pyright: ignore[reportArgumentType]
) -> None:
    # pylint: disable=import-outside-toplevel)
    from searx.engines import engines
    from searx import settings

    # pylint: enable=import-outside-toplevel)

    settings_engines = settings_engines or settings['engines']
    settings_outgoing = settings_outgoing or settings['outgoing']

    # Tor-only build: the settings are checked before the networks are
    # replaced (searx.init_settings has checked them already)
    check_tor_only(settings_outgoing)

    tor_circuits = int(settings_outgoing.get('tor_circuits', 0) or 0)
    if not 0 <= tor_circuits <= TOR_CIRCUITS_MAX:
        raise ValueError(f'outgoing.tor_circuits: {tor_circuits} is not in the range 0..{TOR_CIRCUITS_MAX}')

    default_params: dict[str, t.Any] = {
        'enable_http': False,
        'verify': settings_outgoing['verify'],
        'enable_http2': settings_outgoing['enable_http2'],
        'enable_http3': False,
        'max_connections': settings_outgoing['pool_connections'],
        'local_addresses': settings_outgoing['source_ips'],
        'using_tor_proxy': settings_outgoing['using_tor_proxy'],
        'proxies': settings_outgoing['proxies'],
        'max_redirects': settings_outgoing['max_redirects'],
        'retries': settings_outgoing['retries'],
        'retry_on_http_error': False,
        'tor_circuits': tor_circuits,
    }

    def new_network(params: dict[str, t.Any], logger_name: str | None = None):
        nonlocal default_params
        result = {}
        result.update(default_params)  # pyright: ignore[reportUnknownMemberType]
        result.update(params)  # pyright: ignore[reportUnknownMemberType]
        # Tor-only build: a network can't opt out of Tor (compare
        # searx.engines.using_tor_proxy)
        result['using_tor_proxy'] = True
        if logger_name:
            result['logger_name'] = logger_name
        return Network(**result)  # type: ignore

    def iter_networks():
        nonlocal settings_engines
        for engine_spec in settings_engines:
            engine_name = engine_spec['name']
            engine = engines.get(engine_name)
            if engine is None:
                continue
            network = getattr(engine, 'network', None)
            yield engine_name, engine, network

    if NETWORKS:
        done()
    NETWORKS.clear()
    NETWORKS[DEFAULT_NAME] = new_network({}, logger_name='default')
    NETWORKS['ipv4'] = new_network({'local_addresses': '0.0.0.0'}, logger_name='ipv4')
    NETWORKS['ipv6'] = new_network({'local_addresses': '::'}, logger_name='ipv6')

    # define networks from outgoing.networks
    for network_name, network in settings_outgoing['networks'].items():
        NETWORKS[network_name] = new_network(network, logger_name=network_name)

    # define networks from engines.[i].network (except references)
    for engine_name, engine, network in iter_networks():
        if network is None:
            network = {}
            for attribute_name, attribute_value in default_params.items():
                if hasattr(engine, attribute_name):
                    network[attribute_name] = getattr(engine, attribute_name)
                else:
                    network[attribute_name] = attribute_value
            NETWORKS[engine_name] = new_network(network, logger_name=engine_name)
        elif isinstance(network, dict):
            NETWORKS[engine_name] = new_network(network, logger_name=engine_name)

    # define networks from engines.[i].network (references)
    for engine_name, engine, network in iter_networks():
        if isinstance(network, str):
            NETWORKS[engine_name] = NETWORKS[network]

    # the /image_proxy endpoint has a dedicated network.
    # same parameters than the default network, but HTTP/2 is disabled.
    # It decreases the CPU load average, and the total time is more or less the same
    if 'image_proxy' not in NETWORKS:
        image_proxy_params = default_params.copy()
        image_proxy_params['enable_http2'] = False
        NETWORKS['image_proxy'] = new_network(image_proxy_params, logger_name='image_proxy')


@atexit.register
def done():
    """Close all HTTP client

    Note: since Network.aclose has to be async, it is not possible to call this method on Network.__del__
    So Network.aclose is called here using atexit.register
    """
    try:
        loop = get_loop()
        if loop:
            future = asyncio.run_coroutine_threadsafe(Network.aclose_all(), loop)
            # wait 3 seconds to close the HTTP clients
            future.result(3)
    finally:
        NETWORKS.clear()
        NETWORKS[DEFAULT_NAME] = NOT_INITIALIZED


NOT_INITIALIZED = Network(logger_name='not_initialized')
"""Fail-closed placeholder of the default network until :py:obj:`initialize`
has configured the networks from the settings (Tor).  There is no direct
connection: a request through this network raises a :py:obj:`RuntimeError`
(:py:obj:`NOT_INITIALIZED_MESSAGE`), see :py:obj:`Network.get_client`."""

NETWORKS[DEFAULT_NAME] = NOT_INITIALIZED
